CREATE DATABASE CRUD_react_Django;
CREATE TABLE IF NOT EXISTS product (
   key_p int NOT NULL AUTO_INCREMENT, 
   pro_name varchar(90) DEFAULT NULL,     
   pro_provider varchar(50) DEFAULT NULL,     
   pro_existences int DEFAULT NULL,     
   pro_date date DEFAULT NULL,     
   pro_description varchar(400) DEFAULT NULL,     
   pro_category varchar(50) DEFAULT NULL,    
   createdAt timestamp NULL DEFAULT NULL,     
   updatedAt timestamp NULL DEFAULT NULL,     
   PRIMARY KEY (`key_p`) 
   );

   USE crud_react_django;

   INSERT INTO `crud_react_django`.`product` (`pro_name`, `pro_provider`, `pro_existences`, `pro_date`, `pro_description`, `pro_category`) VALUES  
   ('Milanesa de Res', 'La Suiza', 15, '2021/07/07', 'Milanesa de Res', 'Cárnicos'), 
   ('Milanesa de Cerdo', 'Pork Colombia', 5, '2021/10/04', 'Milanesa de Cerdo', 'Cárnicos'), 
   ('Carne molida de Res Premium', 'Club Ganadero', 8, '2018/10/09', 'Carne Molida Premium baja en grasa por 500Gr', 'Cárnicos'), 
   ('Carne Molida', 'Fontana', 10, '2020/10/15', 'Carne molida', 'Cárnicos'), 
   ('Pollo entero con viceras', 'yo soy el pollo', 10, '2021/09/10', 'Pollo entero con viceras marinado.', 'Cárnicos'), 
   ('Pierna pernil de Pollo', 'Calimio', 12, '2020/06/10', 'pierna pernil paquete por 5 cuatro unidades', 'Cárnicos'), 
   ('Mollejas y corazones', 'El pollicia', 14, '2020/08/09', 'Mollejas y corazones para salteado, paquete por 500 gr', 'Cárnicos'), 
   ('Pierna de Cerdo', 'el Chancho', 10, '2017/10/01', 'Pierna de cerdo entera para asar', 'Cárnicos'), 
   ('Costillas de cerdo BBq', 'El Marrano', 15, '2018/09/15', 'Costillas para asar marinadas en salsa BBQ', 'Cárnicos'), 
   ('Pezuña de Cerdo', 'La Fazenda', 5, '2020/08/18', 'Pezuña de cerdo cortada', 'Cárnicos'), 
   ('Queso', 'colanta', 3, '2021-08-20', 'Rico en nutrientes.', 'Lacteos'), 
   ('Leche', 'colanta', 1, '2021-10-07', 'Te ayuda a una fácil digestión disminuyendo molestias pesadez, malestar abdominal causado por la lactosa., ', 'Lacteos'), 
   ('yogurt', 'colanta', 8, '2021-10-07', 'yogurt descremado con trozos de fruta que contiene probióticos que ayudan a mejorar la regeneración de la flora intestinal sin azúcar adicionado. Ideal para complementar tu alimentación balanceada y el ejercicio físico.', 'Lacteos'), 
   ('Mantequilla', 'Alpina', 10, '2021-10-07', 'La Mantequilla Alpina es un producto lácteo elaborado principalmente a base de crema de leche pasteurizada. Es un alimento que aporta calorías al organismo, su aporte nutricional está dado básicamente por su contenido de grasa. Para mantener el producto fresco, consérvese refrigerado una vez abierto. Encuéntrala en presentación Bloque Sin Sal', 'Lacteos'), 
   ('Nata', 'Mimos', 15, '2021-10-07', 'Helado dietético de nata ideal para disfrutar cuidándose en cualquier momento del día., ', 'Lacteos'), 
   ('Kéfir', 'pasco', 11, '2021-10-07', 'Acompaña tus comidas favoritas y comparte junto a los que más aprecias, hechas con los mejores estándares de calidad ', 'Lacteos'), 
   ('Leche en polvo', 'colanta', 2, '2021-10-07', 'Los mejores nutrientes y las proteínas necesarias para tu cuerpo ', 'Lacteos'), 
   ('Leche condensada', 'nestle', 8, '2021-10-07', 'Leche condensada azucarada semidescremada LA LECHERA , con su Tradición y Sabor Único es ideal para tus preparaciones dulces y acompañar como topping tus comidas o bebidas favoritas. ', 'Lacteos'), 
   ('Leche de fórmula para bebés', 'Enfagrow', 5, '2021-10-07', 'La fórmula mejorada de Enfagrow Premium, ahora con MFGM, tiene DHA* y una innovadora combinación de componentes y nutrientes esenciales. ', 'Lacteos'), 
   ('Crema de leche', 'Alpina', 9, '2021-10-07', 'Acompaña tus comidas con la mejor crema de leche', 'Lacteos'),
   ('Salchicha Ranchera', 'Zenu', 15, '2021/10/07', 'La recompensa al mejor sabor del rancho se lo llevan esta jugosa y doradita salchicha. Prepárala asada y siente su inigualable sabor.', 'Embutidos'), 
   ('Chorizo Santarrosano', 'Zenu', 10, '2021/10/08', 'Chorizo de cerdo tipo Santarrosano. Puedes freírlo o asarlo, comértelo al desayuno, al almuerzo, para cenar o para picar. Como sea que lo disfrutes, te aseguramos que vas a comerte un chorizo con gran sabor, calidad y reducido en sodio.', 'Embutidos'), 
   ('Hamburguesa de Res Zenú', 'Zenu', 20, '2021/11/09', 'Llena tus comidas de sabor y practicidad, disfruta de una Hamburguesa de res Zenú 25% reducida en sodio en tan solo 4 minutos.', 'Embutidos'), 
   ('Mortadela de Pollo Zenú', 'Zenu', 11, '2021/11/28', 'La opción ideal para brindarle sabor y nutrición a tu familia, ya que es 25% reducida en sodio, es buena fuente de proteína y sabe muy bien en cualquier momento. ', 'Embutidos'), 
   ('Morcilla Zenú', 'Zenu', 14, '2021/12/26', 'Para tus asados, Zenú te trae toda la tradición y sabor de la morcilla casera, garantizándote las mejores materias primas y los más altos estándares de calidad.', 'Embutidos'), 
   ('Tocineta Ahumada Zenú', 'Zenu', 15, '2021/12/14', 'Al desayuno, almuerzo y comida, acompaña tus más deliciosos platos con Tocineta ahumada Zenú y llénalos de sabor.', 'Embutidos'), 
   ('Cerveroni Zenú', 'Zenu', 20, '2022/04/09', 'Con un sabor ahumado, hecho de cerdo, pollo y res; un Cerveroni Zenú te va a encantar para almorzar, desayunar, cenar o picar. Además, alcanza para compartir con todos, si quieres.', 'Embutidos'), 
   ('Jamoneta Zenú', 'Zenu', 22, '2021/11/01', 'No solo el 25% reducida en sodio y buena fuente de proteína, sino que es la solución perfecta para disfrutar un antojo o complementar tus comidas.', 'Embutidos'), 
   ('Salchicha perro con trozos de queso', 'Zenu', 37, '2023/02/23', 'Es una alternativa deliciosa para disfrutar y alimentarte. Una deliciosa salchicha Perro con trozos de queso Sabana de Alpina que hará de todos tus momentos una experiencia especial.', 'Embutidos'), 
   ('Salchichón de Pollo Zenú', 'Zenu', 26, '2022/07/18', 'Disfrútalo solo o compártelo si quieres, en tus comidas, picadas, cuando quieras y donde quieras. Es un producto 25% reducido en sodio y de alto valor proteico.', 'Embutidos'),
   ('Smirnoff', 'Diageo', 15, '2020/11/28', 'Tipo de vodka de origen ruso se puden conseguir de diferentes sabores', 'Bebidas y licores'), 
   ('San Miguel', 'San Miguel Corporation', 5, '2021/01/14', 'Es la ginebra de mayor venta en el mundo', 'Bebidas y licores'),
   ('Emperador', 'Emperador Distillers', 8, '2018/03/09', 'Es un brandy tremendamente especial, ya que es mucho más dulce que sus competidores.', 'Bebidas y licores'), 
   ('Bacardi', 'Diageo', 11, '2020/03/28', 'Ron Blanco, seco y sútil, con notas de vainilla y almendra.', 'Bebidas y licores'),
   ('Canada Dry', 'The Coca-Cola company', 14, '2021/04/26', 'Canada Dry es una marca de sodas comercializada por Dr Pepper/Seven Up.', 'Bebidas y licores'), 
   ('Fanta', 'The Coca-Cola company', 15, '2020/06/14', 'Fanta es  una bebida gseosa Posee múltiples sabores. Entre ellos, los más tradicionales son el de naranja y el de limón.', 'Bebidas y licores'), 
   ('Pepsi', 'PepsiCo', 13, '2020/04/09', 'Pepsi, también conocida como Pepsi-Cola, es una gaseosa de cola', 'Bebidas y licores'), 
   ('Jack Daniels', 'Dislicores', 22, '2017/11/01', 'El whisky Jack Daniels es filtrado en carbón de arce sacarino, dándole un sabor y aroma distintivos. ', 'Bebidas y licores'), 
   ('Seven Up', 'Postobon', 07, '2018/02/23', '7UP! Su sabor refrescante se puede mezclar con toda clase de bebidas y cocteles.', 'Bebidas y licores'), 
   ('Pony Malta', 'Bavaria', 26, '2020/07/18', 'Pony Malta es una bebida maltosa no alcohólica a base de malta', 'Bebidas y licores'),
   ('Frijol', 'SuDespensa', 15, '2020-08-12 08:05:00', 'Frijol bola roja', 'Granos'), 
   ('Arveja Verde', 'Maritza', 17, '2020-09-15 12:20:00', 'Arveja verde desgranada', 'Granos'), 
   ('Lenteja', 'SuDespensa', 16, '2020-07-24 11:05:00', 'Lenteja seca', 'Granos'), 
   ('Garbanzo', 'Diana', 14, '2021-06-28 09:22:00', 'Garbanzo seco', 'Granos'), 
   ('Arroz', 'Roa', 15, '2021-10-19 08:45:00', 'Arroz blanco', 'Granos'), 
   ('Frijol Blanquillo', 'Aburrá', 16, '2020-05-07 07:55:00', 'Frijol bola blanquillo', 'Granos'), 
   ('Maíz Peto', 'SuDespensa', 14, '2020-11-25 09:30:00', 'Maíz peto grano seco', 'Granos'), 
   ('Cuchuco de Maíz', 'GranosPeter', 13, '2021-10-27 14:25:00', 'Cuchuco de maíz ceco', 'Granos'), 
   ('Frijol Negro', 'Gastronoy Granos', 15, '2021-09-08 13:35:00', 'Frijol bola negra', 'Granos'), 
   ('Cebada Perlada', 'DelCultivo', 12, '2021-10-28 12:54:00', 'Cebada perlada seco', 'Granos'),
   ('Dulces Gomas Aros GRISSLY', 'Colombina', 19, '2020/04/05 18:00:00', 'Gomas azucaradas en forma de aros, sabor a durazno, fresa y manzana verde, paquete de 50 unidades de 6 gramos cada una', 'Dulcería'), 
   ('Galletas Dulces Original OREO', 'Oreo', 12, '2018/10/09 10:20:00', 'galletas circulares de chocolate con un relleno dulce blanco', 'Dulcería'), 
   ('Dulces Werthers Caramelo', 'Storck', 24, '2021/05/25 1:30:00', 'Deliciosos caramelos duros, sin azúcar… ¡para que endulces tu día! El sabor de Werthers es simplemente incomparable. Presentación en bolsa de 70 g. Importado de Alemania.', 'Dulcería'), 
   ('Galletas Dulces Sultana', 'Noel', 9, '2021/02/13 3:00:00', 'Galleta Dulce', 'Dulcería'), 
   ('Bon Bon Bum Fresa', 'Colombina', 15, '2020/01/25 02:30:00', 'Disfruta de Chupeta Bon Bon Bum rojo fresa x 24und en cualquier lugar y cualquier momento', 'Dulcería'), 
   ('Detodito', 'Detodito', 20, '2019/05/05 07:00:00', 'Surtido Bbq Paketon X 6 Unds DETODITO 270 Gramo', 'Dulcería'), 
   ('Caramelo Blanco Con Café', 'Colombina', 30, '2019/04/23 08:00:00', 'disfruta de Dulce Coffee Delight Caramelo x 100und en cualquier lugar y cualquier momento', 'Dulcería'), 
   ('ChocoBreak', 'Colombina', 15, '2021/09/12 11:00:00', 'Este chocolate tiene coco con un relleno delicioso que es como una crema de coco, y encima le ponen algo de coco rallado', 'Dulcería'), 
   ('Turron Supercoco', 'supercoco', 12, '2018/12/24 03:20:00', 'Este delicioso dulce no debe faltar en tus fiestas, fácil de masticar, en la porción perfecta para tus fiestas', 'Dulcería'), 
   ('Arequipe Levapan', 'Levapan', 19, '2018/09/20 02:50:00', 'producto lácteo espeso y dulce producto de la cocción de leche con azúcar, y que generalmente se utiliza como cobertura de postres, o para untar o jaspear', 'Dulcería'),
   ('JABON DETERGENTE LIQUIDO', 'COCO VARELA', 16, '2017-10-25 20:00:00', '2 X 3 LITROS PARA PRENDAS DELICADAS Detergente desarrollado para el lavado de prendas delicadas', 'Elementos de Aseo'), 
   ('Detergente polvo jabón rey', 'Dersa', 5, '2019-03-15 18:30:00', 'Disfruta del mejor aroma del Detergente Dersa polvo bicarbonato + jabon rey x 6000g', 'Elementos de Aseo'), 
   ('Jabon liquido vainilla coco', 'Bacterion', 15, '2019-10-20 10:30:00', 'Lleva tu Jabon liquido Bacterion vainilla coco x1000 ml y protegete de las bacterias durante el dia', 'Elementos de Aseo'), 
   ('Jabón liquido antibacterial frutos tropicales',  'Capibell', 18, '2011-05-21 22:40:00', 'Lleva ahora Jabón Capibell liquido antibacterial frutos tropicales x 1700ml', 'Elementos de Aseo'), 
   ('Jabón liquido aqua bambú', 'Aromasense', 21, '2018-04-10 20:50:10', 'Brindan la mejor experiencia de Cuidado Completo para la piel: limpieza, hidratación, suavidad y un cuativante aroma..', 'Elementos de Aseo'), 
   ('Jabón Liquido Desinfectante Avena', 'Dersa ', 4, '2021-05-20 20:30:00', 'Su fórmula con avena ayuda a cuidar tu piel, removiendo impurezas suavemente.', 'Elementos de Aseo'), 
   ('Jabón Líquido Fragancia Minions', 'Aromatel', 15, '2020-05-26 07:10:00', 'Ayuda a limpiar la piel, convirtiendo el momento del baño en una experiencia refrescante y llena de diversión.', 'Elementos de Aseo'), 
   ('Detergente Polvo Max', 'Ariel', 33, '2021-05-11 20:10:30', 'Detergente, ideal para remover la suciedad de tu ropa.', 'Elementos de Aseo'), 
   ('Detergente Polvo Coco y Menta', 'Rindex ', 12, '2021-11-11 10:10:10', 'Detergente en polvo para lavar ropa blanca y de color. Su nueva fórmula esta especialmente diseñada.', 'Elementos de Aseo'), 
   ('Suavizante Fresca Primavera', 'Suavitel', 17, '2011-11-11 11:11:11', 'Su nueva fórmula con fragancia fresca primavera libera agentes acondicionadores que al contacto con el agua.', 'Elementos de Aseo'),
   ('Cepillo de dientes', 'Colgate', 20, '2022-10-15', 'Cepillo dental ultra soft colgate 1 und', 'Aseo personal'), 
   ('Shampoo', 'Savital', 10, '2022-10-14', 'Shampoo con keratina savital 550ml', 'Aseo personal'), 
   ('Desodorante', 'Speed stick', 15, '2022-10-10', 'Desodorante crema 24/7 cool night 48 horas speed stick 2X50ml', 'Aseo personal'), 
   ('Crema dental', 'Colgate', 24, '2022-10-21', 'Crema dental menta anticaries colgate 150 ml', 'Aseo personal'), 
   ('Seda dental', 'Fluocarden', 27, '2022-11-23', 'Seda dental prevención caries fluocarden 100 mts', 'Aseo personal'), 
   ('Afeitadora', 'Philips', 15, '2022-10-27', 'Afeitadora philips cortadora multiusos norelco series 3000', 'Aseo personal'), 
   ('Acondicionador', 'Savital', 23, '2022-08-29', 'Acondicionador savital argán X 530 ml', 'Aseo personal'), 
   ('Crema para peinar', 'Savital', 2, '2022-07-23', 'Crema para peinar savital biotina X 275 ml', 'Aseo personal'), 
   ('Agua miselar', 'Garnier skin active', 20, '2022-08-25', 'Agua miselar original garnier skin active 400ml', 'Aseo personal'), 
   ('Gel para cabello', 'Ego', 20, '2022-07-13', 'Ego gel attraction X 500 ml', 'Aseo personal'),
   ('Cebolla', 'Maury Fruver', 25, '2022-11-20', ' la cebolla, es una planta herbácea bienal perteneciente a la familia de las amarilidáceas.', 'Vegetales y Frutas'), 
   ('Lechuga', 'Maury Fruver', 20, '2022-1-14', 'Lactuca sativa, conocida comúnmente como lechuga, es una planta herbácea propia de las regiones semitempladas que se cultiva como alimento', 'Vegetales y Frutas'), 
   ('Mora', 'Maury Fruver', 30, '2022-02-15', 'Mora es el nombre que reciben diversos frutos comestibles de distintas especies; cuya fruta no es una baya, sino un eterio', 'Vegetales y Frutas'), 
   ('Papaya', 'Maury Fruver', 22, '2022-10-21', 'Carica papaya es una planta herbácea del género Carica en la familia Caricaceae', 'Vegetales y Frutas'), 
   ('Coco', 'Maury Fruver', 23, '2022-11-23', 'El coco es una fruta obtenida principalmente de la especie tropical cocotero', 'Vegetales y Frutas'), 
   ('Fresas', 'Maury Fruver', 95, '2022-06-27', 'Fragaria, llamado comúnmente fresa o frutilla, es un género de plantas rastreras estoloníferas de la familia Rosaceae.', 'Vegetales y Frutas'), 
   ('Platano', 'Maury Fruver', 13, '2022-07-22', 'Un plátano es una fruta comestible alargada, botánicamente una baya, producida por varios tipos de grandes plantas herbáceas con flores del género Musa', 'Vegetales y Frutas'), 
   ('Limones', 'Maury Fruver', 61, '2022-02-24', 'El limonero, es un pequeño árbol frutal perenne. Su fruto es el limón ​ o citrón, ​ una fruta comestible de sabor ácido y extremadamente fragante que se usa principalmente en la alimentación', 'Vegetales y Frutas'), 
   ('Tomate', 'Maury Fruver', 80, '2022-08-25', 'El tomate es la baya comestible de la planta Solanum lycopersicum, comúnmente conocida como planta de tomate', 'Vegetales y Frutas'), 
   ('Piña', 'Maury Fruver', 20, '2022-07-13', 'nativa de América del Sur. Planta de escaso porte y con hojas duras y lanceoladas de hasta 1 m de largo, fructifica una vez al año produciendo un único fruto fragante y dulce', 'Vegetales y Frutas'),
   ('Fabuloso Antibacterial Floral x3L', 'LLLL', 12, '2021-10-08', 'Fabuloso Frescura Activa Antibacterial. Limpiador multiusos. Con partículas activas y fragancias concentradas.','Desinfectantes'), 
   ('Ajax Bicarbonato Naranja-Limón x3L', 'LLLL', 13, '2021-10-08', 'Limpieza profunda y brillo. Ajax con bicarbonato para todas las superficies', 'Desinfectantes'), 
   ('Ajax Bicloro x2L', 'LLLL', 14, '2021-10-08', 'Limpiador líquido concentrado. Quita manchas díficiles', 'Desinfectantes'), 
   ('Fabuloso Fresca Lavanda x2L', 'LLLL', 15, '2021-10-08', ' Limpiador multiusos. Con partículas activas y fragancias concentradas','Desinfectantes'), 
   ('Ajax Bicarbonato Naranja-Limón x1L', 'LLLL', 16, '2021-10-08', 'Limpieza profunda y brillo. Ajax con bicarbonato para todas las superficies', 'Desinfectantes'), 
   ('Fabuloso Alternativa Al Cloro Fresco Amanecer x1.5L', 'LLLL', 17, '2021-10-08', 'Remueve poderosamente manchas díficiles,', 'Desinfectantes'), 
   ('Desinfectante lavanda x5000ml', 'LLLL', 18, '2021-10-08', 'Limpiador desinfectante aroma lavanda', 'Desinfectantes'), 
   ('lavanda Binner x 2 L', 'LLLL', 19, '2021-10-08', 'Limpiador de piso brillo desinfectante lavanda Binner', 'Desinfectantes'), 
   ('Fabuloso Mar Fresco Multiusos x2L', 'LLLL', 20, '2021-10-08', 'Fabuloso Frescura Activa Antibacterial. Limpiador multiusos', 'Desinfectantes'), 
   ('Sanpic lavanda x5000ml', 'LLLL', 21, '2021-10-08', 'Sanpic es un limpiador multiusos que perfuma todo el día', 'Desinfectantes'), 
   ('Bambú Pinolina x 2000ml', 'LLLL', 22, '2021-10-08', 'Productos cuya función es el cuidado general de pisos', 'Desinfectantes'), 
   ('Citronela Pinolina x 3785ml', 'LLLL', 23, '2021-10-08', 'Desinfectante Limpia y Perfuma Tu Hogar Citronela Pinolina','Desinfectantes'), 
   ('Binner mora yerbabuena x1L', 'LLLL', 24, '2021-10-08', 'Desinfectante Binner piso sano mora yerbabuena', 'Desinfectantes'), 
   ('Binner menta y pomelo x1L', 'LLLL', 23, '2021-10-08', 'Desinfectante Binner piso sano menta y pomelo', 'Desinfectantes'), 
   ('Mr Musculo multiusos x 500ml', 'LLLL', 22, '2021-10-08', 'Desinfectante Mr Musculo multiusos','Desinfectantes'), 
   ('Ajax limón biodegradables x40und', 'LLLL', 21, '2021-10-08', 'Toallitas Ajax desinfectantes limón biodegradables', 'Desinfectantes'), 
   ('Pinolina advanced citronela x 960ml', 'LLLL', 20, '2021-10-08', 'Desinfectante Pinolina advanced citronela ', 'Desinfectantes'), 
   ('Pinolina vinagre manzana verde x 1000ml', 'LLLL', 19, '2021-10-08', 'Desinfectante Pinolina vinagre manzana verde', 'Desinfectantes');


CREATE TABLE IF NOT EXISTS employees ( 
   em_id int NOT NULL AUTO_INCREMENT,     
   em_name varchar(50) DEFAULT NULL,     
   em_lastName varchar(50) DEFAULT NULL,
   em_phone int DEFAULT NULL,     
   en_stall VARCHAR(15),   
   PRIMARY KEY (`em_id`) 
   );
   