# Generated by Django 3.2.8 on 2021-10-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(blank=True, max_length=90, verbose_name='Nombre')),
                ('pro_provider', models.CharField(blank=True, max_length=50, verbose_name='Provedor')),
                ('pro_existences', models.IntegerField(blank=True, verbose_name='Existentes')),
                ('pro_date', models.DateField(auto_now=True, verbose_name='Fecha')),
                ('pro_description', models.TextField(verbose_name='Descripción')),
                ('pro_category', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
        ),
    ]
